### ISSUE TITLE
测试图片为什么要crop掉那么多像素

### ISSUE THREAD

**Issue by CCjiahao** [The-Learning-And-Vision-Atelier-LAVA/ArbSR#15]
1. 为什么在做测试的时候要crop掉这么多的像素？
我没有怀疑这样做的公平性，如果对比实验也是这样做的，公平性不容置疑。
但是总觉得crop这么多像素不太合理，比如1.55倍在测试的时候，图片的长宽会mod 31，感觉有点多
2. 是否可以提供一下EDSR的pth文件以及代码？

**Comment by LongguangWang** [comment]
Hi @CCjiahao，感谢对我们工作的关注。
1. 之所以crop掉很多像素，是为了保证在小数放大倍数下HR图像能够被放大倍率整除，这样得到的lr图像才是整数像素大小。比如x1.55时，为了保证HR能够被1.55整除，需要其长宽为31的倍数。
2. 后续对EDSR预训练模型整理后，我们会更新到这个repo中。

**Comment by CCjiahao** [comment]
嗯嗯，明白了，多谢回复！
